# AppVeyor CI build file, https://ci.appveyor.com/project/odinserj/hangfire

# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Please don't edit manually, use the `build.bat version` command instead
version: 0.2.0-build-0{build}

image: Visual Studio 2022

environment:
  SIGNPATH_API_TOKEN:
    secure: PNb7xYHfAcpf2N/CQeWt4ODcpca0Mho819qqRGxYI9ILG8Nrw14UWGLca8cCvsgo

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - ps: Install-Module -Name SignPath

build_script: build.bat sign

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'build\**\*.nupkg'
  - path: 'build\**\*.zip'

deploy:
  - provider: NuGet
    api_key: 
      secure: yn2LOv1vM/Yv1AiNSTjuR31GeB+EI/OrtZfqwdrZelpPWTICr77eSAaAb5c0HMPC
    on:
      appveyor_repo_tag: true
